fx_version 'cerulean'
game 'gta5'
lua54 'yes'
author 'Kakarot'
description 'Allows players to rob specific trucks for money and items'
version '1.5.0'

shared_script 'config.lua'
client_script 'client.lua'
server_script 'server.lua'
